export enum ListGenreAnimePic {
  // SFW
  Neko = 'neko',
  SFWFoxes = 'sfwfoxes',
  Husbu = 'husbu',
  Inori = 'inori',
  LoliSFW = 'lolisfw',
  RandomSFW = 'randomsfw',
  Shota = 'shota',
  WallpaperSFW = 'wallpapersfw',

  // NSFW
  Ass = 'ass',
  BDSM = 'bdsm',
  Blowjob = 'blowjob',
  Cum = 'cum',
  Doujin = 'doujin',
  Feet = 'feet',
  Femdom = 'femdom',
  FoxGirl = 'foxgirl',
  Glasses = 'glasses',
  Hentai = 'hentai',
  Loli = 'loli',
  Netorare = 'netorare',
  Maid = 'maid',
  Masturbation = 'masturbation',
  Orgy = 'orgy',
  Panties = 'panties',
  Pussy = 'pussy',
  School = 'school',
  Succubus = 'succubus',
  Tentacles = 'tentacles',
  Thighs = 'thighs',
  UglyBastard = 'uglybastard',
  Uniform = 'uniform',
  Yuri = 'yuri',
  Yaoi = 'yaoi',
  ZettaiRyouiki = 'zettaiRyouiki',
  WallpaperNSFW = 'wallpapernsfw',
}

export enum SpeechLangList {
  English = 'en',
  Korean = 'kr',
  Japanese = 'jp',
  Spanish = 'es',
  French = 'fr',
  Brazilian = 'br',
  Mandarin = 'cn',
  Dutch = 'nl',
  Arabic = 'ar',
  Italian = 'it',
  German = 'de',
}

export enum QuoteGenreList {
  Random = 'random',
  Kanye = 'kanye',
  Agamis = 'agamis',
}
